version: '3.5'

services:
 order-item-client:
    image: order-item-client
    networks:
      - client
    build:
      context: .
      dockerfile: ./Dockerfile      
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    stdin_open: true

networks:
  client:
   name: global
  